EricFillion/happy-transformer

- .gitignore
- happy_transformer/happy_bert.py
- happy_transformer/happy_transformer.py
- main.py
> Created HappyTransformer parent class and HappyBERT child class

- happy_transformer/happy_bert.py
- happy_transformer/happy_roberta.py
- testing/test_bert.py
- testing/test_roberta.py
> Updating tests to work with pytest framework

- happy_transformer/happy_gpt2.py
- happy_transformer/happy_xlm.py
Known problems with GPT-2:
I had to rewrite __get_segment_ids since gpt2 tokens are not set.
I had to rewrite __get_prediction_index to just index '<mask>'
> Basic implementation of GPT2 and XLM

- happy_transformer/happy_bert.py
- happy_transformer/happy_transformer.py
Changed method names in HappyTransformer and moved HappyBERT's _get_prediction_softmax to the child class
> HappyBERT masked word prediction modification 

- happytransformer/happy_transformer.py
- happytransformer/mlm_utils.py
> finetuning support

- happytransformer/happy_transformer.py
- happytransformer/mlm_utils.py
- tests/load_transformer.py
Logs now only show output from happytransformer. Download bars still display
> Cleaned up logging

- happytransformer/happy_bert.py
> 🐛 QA scores

- happytransformer/happy_transformer.py
fix the bug that the model does not run on gpu at all...
> add the gpu cuda movement

- happytransformer/happy_transformer.py
> 🐛 Fixed cpu support for mlm

- happytransformer/happy_transformer.py
- tests/test_predict.py
Corrects behaviour where first options are always selected instead of best options
> Fix MLM predictions when options supplied

- happytransformer/sequence_classifier.py
- tests/test_sequence.csv
- tests/test_sequence.py
`tqdm_notebook()` was being used, which requires unnecessary imports. Replaced with `tqdm()`.
Also updated some formatting.
> Fix tqdm progress bar

- README.md
This would make the README more decipherable for users looking to jump ahead to sections.
Not adding an issue for this unless it's needed for approval, seems trivial.
> Improvement/Suggestion: Add README table of contents

- happytransformer/happy_bert.py
- happytransformer/happy_roberta.py
- happytransformer/happy_transformer.py
- happytransformer/happy_xlnet.py
also removed obsolete variables.
All tests are still passing :sunglasses:
> replaced tokenizers with fast versions

- README.md
- examples/question_answering/readme_examples.py
- happytransformer/happy_question_answering.py
- tests/test_qa.py
**Changes** 
README: 
1. Added QA to the readme 
2. Moved description to the top of the README 
3. Updated tech section  in the README by removing packages we no longer use 
4. Updated call for contributors with the README 
5.  Reorganized Feature table and table of contents (TOC) in order of most common tasks 
6. Deleted various outdated sections of the readme 
Other:
7. Added QA README examples to examples/question_answering/readme_examples.py
8. QA: Changed topk to top_k since that's what we use for WP. 
9. As per 8, updated test cases for QA
> Added QA To README 

- README.md
- examples/next_sentence_prediction/readme_examples.py
- happytransformer/__init__.py
- happytransformer/happy_next_sentence.py
- tests/test_ns.py
**Changes**
- Added readme section for NSP 
- Added readme examples to "examples/next_sentence_prediction/readme_examples.py"
Note: This branch contains the commits from #174 which is waiting for approval by @willmacd.
> Next Sentence Prediction Readme

- happytransformer/__init__.py
- happytransformer/happy_next_sentence.py
- tests/test_ns.py
**Changes** 
- Completed the HappyNextSentence class. Mostly used code from the original Happy Transformer  
- Added tests under test_ns.py. Noticed that it gives a different output each time due to the model's weights being randomly initialized. 
- Included tests for when an exception is raised. We should add similar tests to other test files. 
**Questions**
- Should we rename HappyNextSentence to HappyNextSentencePrediction? 
- Should we change "predict_next_sentence' to "is_next_sentence" or something else. At first glance, people might think "predict_next_sentence" means "generate text to follow a sentence."
> Added Next Sentence Prediction 

- happytransformer/cuda_detect.py
- happytransformer/happy_question_answering.py
- happytransformer/happy_text_classification.py
- happytransformer/happy_word_prediction.py
Grab the actual CUDA device number rather than assuming its 1.
> CUDA Hotfix

- happytransformer/mwp/__init__.py
- happytransformer/qa/__init__.py
- happytransformer/sp/__init__.py
- happytransformer/sp/defauly_args.py
- happytransformer/sp/trainer.py
- happytransformer/tc/__init__.py
- setup.py
**Changes**
1. Added __init__.py files to tc, qa, and mwp folders 
2. Added " packages = find_packages()," to setup.py 
3. Added skeleton code for the NSP trainer. I figured MWP has skeleton code for its trainer, so for consistency we should also include it for NSP.
> PyPi Configuration 

- README.md
- Added news about 2.0.0 
- Removed models for NSP from  features table 
- Added "|" to far right side of the features table.
> Small README Edits

- .gitignore
- examples/text_classification/training_example.py
- Added a training for multi label TC under examples/text_classification/training_example.py. 
- Updated gitignore to include files creates by running this example.
> Added Text Classification Training Example

- .gitignore
- examples/question_answering/training_example.py
- requirements.txt
Added a long example for QA training. 
Do you know a better way of getting the top/bottom n results from the datasets? If you do, feel free to commit straight to the PR. I tried "train_dataset.pop(n)" and "train_dataset.[0:n]"
> QA Training Long Example

- examples/question_answering/training_example.py
- examples/text_classification/training_example.py
> Fixed Print Statements For Long Training Examples

- README.md
- Added a link to a Medium article about word prediction 
- fixed a typo
> Updated WP readme

- README.md
- examples/text_classification/readme_examples.py
- happytransformer/happy_token_classification.py
- tests/test_toc.py
> Added Documentation For Token Classification and Model Support 

- docs/pages/parameters.md
- docs/pages/question-answering/finetuning.md
- docs/pages/save-load-data.md
- docs/pages/text-classification/finetuning.md
- docs/pages/text-generation/basic-usage.md
- docs/pages/text-generation/finetuning.md
- docs/pages/text-generation/instantiation.md
- docs/pages/text-generation/settings.md
- docs/pages/word-prediction/basic-usage.md
- docs/pages/word-prediction/finetuning.md
- examples/generation/readme_examples.py
- happytransformer/__init__.py
- happytransformer/happy_generation.py
- requirements.txt
- tests/__init__.py
- tests/test_gen.py
- tests/test_qa.py
- tests/test_tc.py
- tests/test_wp.py
- Changed the arg field for HappyTextGeneration.generate_text()  from dictionary to dataclass
- Added documentation for save/load preprocssed data 
- Added documentation for dataclass train/test/eval() arg inputs  
- Fixed broken test cases
> Text Generation Arg Input + Documentation 

- docs/_config.yml
- docs/pages/3-news.md
- docs/pages/6-save-load-data.md
- Removed search. It was working when the website was running in localhost. But, it was not working when deployed. 
- Added proper spacing in news 
- Fixed a table in "6-save-load-data.md"
> Small Website Changes

- tests/test_gen.py
- tests/test_ns.py
- tests/test_qa.py
- tests/test_tc.py
- tests/test_wp.py
- also deleted an unneeded import and comment
> Refactored Import Paths for Tests

- README.md
- docs/index.md
- Replaced version badge with PyPI badge 
- Added Discord badge
- Changed "PyPi" to "PyPI" on the website
> README Badges + Website Typo

- docs/index.md
Added new functionality introduced in version 2.2.0 into the feature table on the website's homepage
> Updated Features Table

- docs/pages/1-text-generation/4-finetuning.md
> Added note about running generate_text() after training/evaluating

- docs/pages/1-text-generation/4-finetuning.md
- happytransformer/happy_generation.py
- setup.py
- tests/test_gen.py
- Solves #220 
- Converted the current text generation implementation to use a TextGenerationPipeline(). 
**Testing:** 
I ran all of the tests and they passed. I also git cloned this branch in Google Colab and made sure it worked while connected to a GPU. 
**Potential future changes:** 
As of right now, the text will be tokenized two times. Once to determine the adjusted min/max length and once within the pipeline. In the future we can possibly revert back to a custom implementation to improve performance. For now, I think we should go with using a pipeline to minimize potential bugs.
> Implemented Pipeline For Text Generation 

- docs/pages/1-text-generation/3-settings.md
Before it looked fine in my PyCharm editor but did not convert into a table when deployed to the website. I shorted the top_p row and added a missing "-" to the definition header which fixed it.
> Fixed Text Generation Setting Table

- README.md
- docs/index.md
- docs/pages/1-text-generation/2-basic-usage.md
- docs/pages/2-text-classification/1-instantiation.md
- docs/pages/6-next-sentence/1-instantiation.md
- docs/pages/7-text-to-text/1-instantiation.md
- docs/pages/7-text-to-text/2-basic-usage.md
- docs/pages/7-text-to-text/3-settings.md
- examples/text-to-text/doc_examples.py
- happytransformer/__init__.py
- happytransformer/adaptors/berts.py
- happytransformer/happy_text_to_text.py
- happytransformer/happy_token_classification.py
- happytransformer/tt/__init__.py
- happytransformer/tt/default_args.py
- happytransformer/tt/trainer.py
- setup.py
- tests/test_tt.py
- tests/test_wp.py
- Added text-to-text functionality 
- Fixed a bug regarding using MWP with ALBERT. Sometimes the model would predict a blank string which caused an exception during post-processing. Also added the preventative code to RoBERTa's post-processing method.  
- Fixed little errors within the documentation. 
- Bumped version to 2.2.4
> 2.2.4: Text-to-text and more 

- docs/pages/1-text-generation/3-settings.md
- setup.py
- tests/test_gen.py
Added changes from #258 and #259
> New Version: 2.3.1

- docs/pages/3-news.md
- setup.py
Bumped the version for the changes from #266. Also added news regarding the changes.
> Version 2.3.2

- README.md
- docs/pages/7-text-to-text/1-instantiation.md
- docs/pages/7-text-to-text/2-basic-usage.md
- docs/pages/7-text-to-text/3-settings.md
- docs/pages/7-text-to-text/4-finetuning.md
- setup.py
1. Contains fix from #268
2. Added text-to-text articles to docs to provide additional examples.
> Version 2.3.3

- happytransformer/happy_generation.py
- happytransformer/happy_next_sentence.py
- happytransformer/happy_question_answering.py
- happytransformer/happy_text_classification.py
- happytransformer/happy_text_to_text.py
- happytransformer/happy_token_classification.py
Addresses #270. 
The load_path argument was missing for most of the super() calls within HappyTransformer child classes. This will fix potential bugs that may occur when loading saved models.
> Added missing load_path argument 

- docs/pages/1-text-generation/4-finetuning.md
- docs/pages/2-text-classification/3-finetuning.md
- docs/pages/3-question-answering/3-finetuning.md
- docs/pages/4-word-prediction/3-finetuning.md
- docs/pages/5-parameters.md
- docs/pages/7-text-to-text/4-finetuning.md
- happytransformer/gen/default_args.py
- happytransformer/gen/trainer.py
- happytransformer/happy_trainer.py
- happytransformer/qa/default_args.py
- happytransformer/qa/trainer.py
- happytransformer/tc/default_args.py
- happytransformer/tc/trainer.py
- happytransformer/tt/trainer.py
- happytransformer/wp/default_args.py
- happytransformer/wp/trainer.py
- setup.py
- tests/test_gen.py
- tests/test_tt.py
Implemented the suggestion from #257 by adding the ability to train in half precision for all of the current training functionality.  I also updated the documentation to include reference to these new features and bumped the version to 4.4.0.
> Added half precision training and increased version to 4.4.0 

- setup.py
This version contains the changes from #280
> Increased version to 2.4.1

- docs/pages/2-text-classification/3-finetuning.md
- docs/pages/7-save-load-model.md
> Updated Documentation 
